[package]
name = "strange-config-format"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
jsonxf = "1.1.1"
nom = "7.0.0"
